### ISSUE TITLE
Crossflow Package is not on conda

### ISSUE THREAD

**Issue by 1martinos** [rostaresearch/enhanced-sampling-workshop-2022#1]
https://github.com/rostaresearch/enhanced-sampling-workshop-2022/blob/a7ee35277f45f382d8d9acf7567bbe083cce3a23/requirements.txt#L30

Crossflow package is not available on Conda, leading to an error when attempting to create the environment as described in the README.

**Comment by bertadenes** [comment]
@CharlieLaughton, can you please tell us what is the channel crossflow is available on?

**Comment by bertadenes** [comment]
fixed in 2a95f41675b16bc5a09f7ee093c2fedb99b2d996
tested in linux and windows
