### ISSUE TITLE
Suggestion: Add reference here and for the DHAM paper

### ISSUE THREAD

**Issue by 1martinos** [rostaresearch/enhanced-sampling-workshop-2022#2]
https://github.com/rostaresearch/enhanced-sampling-workshop-2022/blob/a7ee35277f45f382d8d9acf7567bbe083cce3a23/Day1/1.Umbrella_Sampling_NaCl/NaCl_Umbrella_Sampling.ipynb?short_path=7ba99c3#L930

**Comment by bertadenes** [comment]
They are in the text, not the title
