### ISSUE TITLE
Task Unclear

### ISSUE THREAD

**Issue by 1martinos** [rostaresearch/enhanced-sampling-workshop-2022#3]
https://github.com/rostaresearch/enhanced-sampling-workshop-2022/blob/a7ee35277f45f382d8d9acf7567bbe083cce3a23/Day1/1.Umbrella_Sampling_NaCl/NaCl_Umbrella_Sampling.ipynb?short_path=7ba99c3#L325

**Comment by pedrojuanbj** [comment]
I removed it, there is not much to be done in that step.
