### ISSUE TITLE
Image links are broken

### ISSUE THREAD

**Issue by 1martinos** [rostaresearch/enhanced-sampling-workshop-2022#8]
https://github.com/rostaresearch/enhanced-sampling-workshop-2022/blob/369e0bdf735d7e09dfe348f34f1787a30927190d/Day1/4.MLTSA/4.1.Analytical_Model.ipynb?short_path=7948175#L84

https://github.com/rostaresearch/enhanced-sampling-workshop-2022/blob/369e0bdf735d7e09dfe348f34f1787a30927190d/Day1/4.MLTSA/4.1.Analytical_Model.ipynb?short_path=7948175#L99

https://github.com/rostaresearch/enhanced-sampling-workshop-2022/blob/369e0bdf735d7e09dfe348f34f1787a30927190d/Day1/4.MLTSA/4.1.Analytical_Model.ipynb?short_path=7948175#L118

**Comment by 1martinos** [comment]
Looking at them now I assume it's windows links using "\" not "/" potentially?

**Comment by bertadenes** [comment]
Yes I meant to fix them yesterday I remember. I think it is because somehow they are committed as `*.PNG` and linked as `.png`

**Comment by pedrojuanbj** [comment]
This only happens with these? I put the images the same way on the NaCl example and they are just fine?

**Comment by bertadenes** [comment]
fixed in 75edd9ba67a935dd47805ee277b181742a04efb0
